//
//  AutomationSettingsView.swift
//  Acreage
//
//  Created by Tom on 5/31/25.
//
import SwiftUI

struct AutomationSettingsView: View {
    @ObservedObject var manager = AutomationSettingsManager.shared

    var body: some View {
        Form {
            Section(header: Text("Mailing Automation")) {
                Toggle("Require Mail Approval", isOn: $manager.settings.mailApprovalRequired)
                Toggle("Auto-Send Offer Letters", isOn: $manager.settings.offerLetterAutoSendEnabled)
                Toggle("Send Neighbor Letters", isOn: $manager.settings.neighborLetterEnabled)
            }

            Section(header: Text("Document & Disposition Automation")) {
                Toggle("Auto-Generate Deeds", isOn: $manager.settings.autoGenerateDeeds)
                Toggle("Auto-Upload to Marketplace", isOn: $manager.settings.autoUploadToMarketplace)
            }

            Section(header: Text("Capital Management")) {
                Toggle("Enable Capital Manager", isOn: $manager.settings.enableCapitalManagement)
                Toggle("Auto-Pay Property Taxes", isOn: $manager.settings.autoPayTaxes)
            }

            Section(header: Text("Advanced Intelligence")) {
                Toggle("Context-Aware Assistant", isOn: $manager.settings.assistantContextAwarenessEnabled)
                Toggle("Auto-Run Due Diligence", isOn: $manager.settings.autoRunDueDiligence)
                Toggle("Automate Buyer Follow-Up", isOn: $manager.settings.buyerFollowupAutomation)
                Toggle("Use Virtual Mailbox", isOn: $manager.settings.virtualMailboxIntegration)
            }

            Section {
                Button("Reset to Defaults") {
                    manager.resetToDefaults()
                }
                .foregroundColor(.red)
            }
        }
        .navigationTitle("Automation Settings")
        .padding()
    }
}
